# Generated by Django 5.0.6 on 2024-06-14 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='list',
            name='user2',
        ),
        migrations.CreateModel(
            name='SharedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_lists', to='agenda.list')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_lists_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_lists_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
