# Generated by Django 5.0.6 on 2024-06-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_remove_list_user1_remove_list_user2_sharedlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedlist',
            name='list',
        ),
        migrations.AlterField(
            model_name='task',
            name='todo_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agenda.sharedlist'),
        ),
        migrations.AddField(
            model_name='sharedlist',
            name='name',
            field=models.CharField(default='Bucket List', max_length=100),
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
